version: 2.1

orbs:
  ruby: cimg/ruby@1.2.0
  android: cimg/android@3.1.0

executors:
  android-executor:
    docker:
      - image: circleci/android:api-30  # Use CircleCI's Android image with SDK pre-installed
    working_directory: ~/repo

jobs:
  deploy:
    executor: android-executor
    steps:
      - checkout  # Checkout your repository
      - ruby/install-deps
      - run:
          name: Make gradlew executable
          command: chmod +x gradlew
      - run:
          name: Run Fastlane deploy lane
          command: |
            bundle exec fastlane deploy  # Call the 'deploy' lane in your Fastfile

workflows:
  version: 2
  deploy:
    jobs:
      - deploy  # This workflow calls the 'deploy' job defined above
