version: 2.1

orbs:
  ruby: circleci/ruby@1.2.0

executors:
  android-executor:
    docker:
      - image: cimg/android:2025.02 # Use CircleCI's Android image with SDK pre-installed
    working_directory: ~/repo

jobs:
  deploy:
    executor: android-executor
    steps:
      - checkout  # Checkout your repository
      - ruby/install-deps
      - run:
          name: Make gradlew executable
          command: chmod +x gradlew
      - run:
          name: Run Fastlane deploy lane
          command: |
            bundle exec fastlane deploy  # Call the 'deploy' lane in your Fastfile

workflows:
  version: 2
  deploy:
    jobs:
      - deploy  # This workflow calls the 'deploy' job defined above
