version: 2.1

executors:
  android-executor:
    docker:
      - image: circleci/android:latest  # Use CircleCI's Android image with SDK pre-installed
    working_directory: ~/repo

jobs:
  deploy:
    executor: android-executor
    steps:
      - checkout  # Checkout your repository
      - run:
          name: Make gradlew executable
          command: chmod +x gradlew  # Ensure gradlew has executable permissions
      - run:
          name: Install dependencies
          command: |
            gem install bundler:2.5.6
            bundle install --jobs 4 --retry 3  # Install Fastlane and other gems from Gemfile
      - run:
          name: Run Fastlane deploy lane
          command: |
            bundle exec fastlane deploy  # Call the 'deploy' lane in your Fastfile

workflows:
  version: 2
  deploy:
    jobs:
      - deploy  # This workflow calls the 'deploy' job defined above
